In [1]:
import pandas as pd 
import numpy as np

In [2]:
data =pd.read_csv("Placement.csv")

In [3]:
data.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [4]:
data.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

## 1.Quan & qual :

In [5]:
quan=[]
qual=[]
for column in data.columns:
    if data[column].dtypes == "str":
        qual.append(column)
    else:
        quan.append(column)

In [6]:
data.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='str')

In [7]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [8]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

## 2.Data Frame:

In [9]:
# mean,mode,median
# percentile(k\100(n+1))
#IQR and outliers
df=pd.DataFrame(index=["mean","median","mode","q1","q3","IQR","mul*1.5","min","less_range","max","grater_range"],columns=quan)

In [10]:
df

             sl_no ssc_p hsc_p degree_p etest_p mba_p salary
mean           NaN   NaN   NaN      NaN     NaN   NaN    NaN
median         NaN   NaN   NaN      NaN     NaN   NaN    NaN
mode           NaN   NaN   NaN      NaN     NaN   NaN    NaN
q1             NaN   NaN   NaN      NaN     NaN   NaN    NaN
q3             NaN   NaN   NaN      NaN     NaN   NaN    NaN
IQR            NaN   NaN   NaN      NaN     NaN   NaN    NaN
mul*1.5        NaN   NaN   NaN      NaN     NaN   NaN    NaN
min            NaN   NaN   NaN      NaN     NaN   NaN    NaN
less_range     NaN   NaN   NaN      NaN     NaN   NaN    NaN
max            NaN   NaN   NaN      NaN     NaN   NaN    NaN
grater_range   NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [11]:
def quan_qual(data,quan):
    for column in quan:
        df.loc["mean",column]=data[column].mean()
        df.loc["median",column]=data[column].median()
        df.loc["mode",column]=data[column].mode()[0]
        # percentile:
        df.loc["q1",column]=np.percentile(data[column],25)
        df.loc["q3",column]=np.percentile(data[column],75)
        df.loc["min",column]=data[column].min()
        df.loc["max",column]=data[column].max()
        
        # IQR(interquatile range):
        df.loc["IQR",column]= df.loc["q3",column] - df.loc["q1",column]
        df.loc["mul*1.5",column]=1.5 * (df.loc["IQR",column])
        df.loc["less_range",column]=(df.loc["q1",column])-(df.loc["mul*1.5",column])
        df.loc["grater_range",column]= (df.loc["q3",column])+(df.loc["mul*1.5",column])

In [12]:
df

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
q1,54.5,60.6,60.9,61.0,60.0,57.945,NaN
q3,161.5,75.7,73.0,72.0,83.5,66.255,NaN
IQR,107.0,15.1,12.1,11.0,23.5,8.31,NaN
mul*1.5,160.5,22.65,18.15,16.5,35.25,12.465,NaN
min,1,40.89,37.0,50.0,50.0,51.21,200000.0
less_range,-106.0,37.95,42.75,44.5,24.75,45.48,NaN
max,215,89.4,97.7,91.0,98.0,77.89,940000.0
grater_range,322.0,98.35,91.15,88.5,118.75,78.72,NaN

## percentaile:

In [13]:
# df.loc["q1",column]=np.percentile(data[column],25)
#     df.loc["q3",column]=np.percentile(data[column],75)
#     df.loc["min",column]=data[column].min()
#     df.loc["max",column]=data[column].max()

## IQR:

In [14]:
# df.loc["IQR",column]= df.loc["q3",column] - df.loc["q1",column]
#     df.loc["mul*1.5",column]=1.5 * (df.loc["IQR",column])
#     df.loc["less_range",column]=(df.loc["q1",column])-(df.loc["mul*1.5",column])
#     df.loc["grater_range",column]= (df.loc["q3",column])+(df.loc["mul*1.5",column])

## Outlier finding:

In [15]:
lesser=[]
grater=[]
for column in quan:
    if df.loc["less_range",column] > df.loc["min",column]:
        lesser.append(column)
    if df.loc["grater_range",column] < df.loc["max",column]:
        grater.append(column)

In [16]:
print("lesser:",lesser)
print("grater :",grater)

lesser: ['hsc_p']
grater : ['hsc_p', 'degree_p']

## outlier replace method:
## to replace in out original dataset not dataframe:

In [17]:
for column in lesser:
    data.loc[data[column]<df[column]["less_range"],column]=df[column]["less_range"]

In [18]:
for column in grater:
    data.loc[data[column]>df[column]["grater_range"],column]=df[column]["grater_range"]

In [19]:
# data.loc[:,]

In [55]:
# def quan_qual(data,quan):
#     for column in quan:
#         df.loc["mean",column]=data[column].mean()
#         df.loc["median",column]=data[column].median()
#         df.loc["mode",column]=data[column].mode()[0]
#         # percentile:
#         df.loc["q1",column]=np.percentile(data[column],25)
#         df.loc["q3",column]=np.percentile(data[column],75)
#         df.loc["min",column]=data[column].min()
#         df.loc["max",column]=data[column].max()
        
#         # IQR(interquatile range):
#         df.loc["IQR",column]= df.loc["q3",column] - df.loc["q1",column]
#         df.loc["mul*1.5",column]=1.5 * (df.loc["IQR",column])
#         df.loc["less_range",column]=(df.loc["q1",column])-(df.loc["mul*1.5",column])
#         df.loc["grater_range",column]= (df.loc["q3",column])+(df.loc["mul*1.5",column])

In [21]:
df

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,288655.405405
median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
q1,54.5,60.6,60.9,61.0,60.0,57.945,NaN
q3,161.5,75.7,73.0,72.0,83.5,66.255,NaN
IQR,107.0,15.1,12.1,11.0,23.5,8.31,NaN
mul*1.5,160.5,22.65,18.15,16.5,35.25,12.465,NaN
min,1,40.89,42.75,50.0,50.0,51.21,200000.0
less_range,-106.0,37.95,42.75,44.5,24.75,45.48,NaN
max,215,89.4,91.15,88.5,98.0,77.89,940000.0
grater_range,322.0,98.35,91.15,88.5,118.75,78.72,NaN

In [52]:
def Outlier(quan):
    less_out=[]
    high_out=[]
    for column in quan:
        if df.loc["min",column]<df.loc["less_range",column]:
            less_out.append(column)
        if df.loc["max",column]>df.loc["grater_range",column]:
            high_out.append(column)

In [53]:
Outlier(quan)

In [54]:
less_out

[]

In [25]:
data["hsc_p"].value_counts()

hsc_p
63.00    14
62.00    12
67.00     9
60.00     9
64.00     8
         ..
65.50     1
77.60     1
70.20     1
61.40     1
61.33     1
Name: count, Length: 91, dtype: int64

## Frequecy :

### Create a frequency table:

In [26]:
frequency_df=pd.DataFrame(columns=["value","frequency","relative frequecy(%)","cumsum"])

In [28]:
# frequency_df.drop("hsc_p",axis=1)

In [29]:
frequency_df.columns

Index(['value', 'frequency', 'relative frequecy(%)', 'cumsum'], dtype='str')

In [44]:
def Frequency(data,column):
    frequency_df["value"]= data[column].value_counts().index
    frequency_df["frequency"]= data[column].value_counts().values
    frequency_df["relative frequecy(%)"]=(frequency_df["frequency"])/91
    frequency_df["cumsum"]=frequency_df["relative frequecy(%)"].cumsum()

In [42]:
frequency_df.shape

(91, 4)

In [45]:
frequency_df

    value  frequency  relative frequecy(%)    cumsum
0   63.00         14              0.153846  0.153846
1   62.00         12              0.131868  0.285714
2   67.00          9              0.098901  0.384615
3   60.00          9              0.098901  0.483516
4   64.00          8              0.087912  0.571429
..    ...        ...                   ...       ...
86  65.50          1              0.010989  2.318681
87  77.60          1              0.010989  2.329670
88  70.20          1              0.010989  2.340659
89  61.40          1              0.010989  2.351648
90  61.33          1              0.010989  2.362637

[91 rows x 4 columns]

In [36]:
data["hsc_p"]

0      91.00
1      78.33
2      68.00
3      52.00
4      73.60
       ...
210    82.00
211    60.00
212    67.00
213    66.00
214    58.00
Name: hsc_p, Length: 215, dtype: float64