In [1]:
import pandas as pd
import numpy as np

In [57]:
data=pd.read_csv("Placement.csv")

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    str
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    str
 6   hsc_s           215 non-null    str
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    str
 9   workex          215 non-null    str
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    str
 12  mba_p           215 non-null    float64
 13  status          215 non-null    str
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), str(8)
memory usage: 25.3 KB

In [5]:
data.isna().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [9]:
df=pd.DataFrame(index=['mean','mediun','mode'])

In [10]:
df

Empty DataFrame
Columns: []
Index: [mean, mediun, mode]

In [40]:
# ṣeparate quan and qual:

quan=[]
qual=[]
def quan_qual(data):
    for i in data.columns:
        if data[i].dtypes=='str':
            qual.append(i)
        else:
            quan.append(i)
    return quan,qual
print(quan_qual(data))

(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'], ['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status'])

In [41]:
data["ssc_p"].dtypes

dtype('float64')

In [42]:
print(qual)

['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

### Data Frame :

In [65]:
df=pd.DataFrame(index=['mean','median','mode'],columns=quan)

In [66]:
df

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [67]:
# 'mean' row-இன் 'sl_no' column val
df["sl_no"]["mean"]

nan

In [76]:
for column_name in quan:
    df.loc["mean",column_name]=data[column_name].mean()
    df.loc["median",column_name]=data[column_name].median()
    df.loc["mode",column_name]=data[column_name].mode()[0]

In [77]:
df

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
mode,1,62.0,63.0,65.0,60.0,56.7,300000.0