In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("Placement.csv")

In [19]:
pd.set_option("Display.max_columns",None)

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    str
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    str
 6   hsc_s           215 non-null    str
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    str
 9   workex          215 non-null    str
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    str
 12  mba_p           215 non-null    float64
 13  status          215 non-null    str
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), str(8)
memory usage: 25.3 KB

In [5]:
data.isna().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [6]:
df=pd.DataFrame(index=['mean','mediun','mode'])

In [7]:
df

Empty DataFrame
Columns: []
Index: [mean, mediun, mode]

In [8]:
# ṣeparate quan and qual:

quan=[]
qual=[]
def quan_qual(data):
    for i in data.columns:
        if data[i].dtypes=='str':
            qual.append(i)
        else:
            quan.append(i)
    return quan,qual
quan,qual=quan_qual(data)

In [9]:
data["ssc_p"].dtypes

dtype('float64')

In [10]:
print(qual)

['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

### Data Frame :

In [10]:
# df=pd.DataFrame(index=['mean','median','mode',"20%","45%","99%"],columns=quan)

In [11]:
df

Empty DataFrame
Columns: []
Index: [mean, mediun, mode]

In [12]:
# 'mean' row-இன் 'sl_no' column val
# df["sl_no"]["mean"]

In [13]:
# for column_name in quan:
#     df.loc["mean",column_name]=data[column_name].mean()
#     df.loc["median",column_name]=data[column_name].median()
#     df.loc["mode",column_name]=data[column_name].mode()[0]
#     df.loc["20%",column_name]=np.percentile(data[column_name],20)
#     df.loc["45%",column_name]=np.percentile(data[column_name],45)
#     df.loc["99%",column_name]=np.percentile(data[column_name],99)

In [12]:
df

Empty DataFrame
Columns: []
Index: [mean, mediun, mode]

### percentaile :

In [13]:
data.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

## Outlier finding and filter phase:

In [24]:
df=pd.DataFrame(index=['mean','median','mode',"25%","75%","max","IQR","MUL*1.5","upper_outlier","lower_outlier","min","maxx","var","std"],columns=quan)

In [27]:
for column_name in quan:
    df.loc["mean",column_name,]=data[column_name].mean()
    df.loc["median",column_name]=data[column_name].median()
    df.loc["mode",column_name]=data[column_name].mode()[0]
    df.loc["25%",column_name]=np.percentile(data[column_name],25)
    df.loc["75%",column_name]=np.percentile(data[column_name],75)
    df.loc["max",column_name]=np.percentile(data[column_name],100)
    df.loc['IQR',column_name]=(df.loc["75%",column_name])-(df.loc["25%",column_name])
    df.loc["MUL*1.5",column_name]=1.5 * ( df.loc['IQR',column_name])
    df.loc["upper_outlier",column_name]=(df.loc["75%",column_name])+df.loc["MUL*1.5",column_name]
    df.loc["lower_outlier",column_name]=(df.loc["25%",column_name]-df.loc["MUL*1.5",column_name])
    df.loc["min",column_name]=data[column_name].min()
    df.loc["maaxx",column_name]=data[column_name].max()
    # var and std
    df.loc["var",column_name]=data[column_name].var()
    df.loc["std",column_name]=data[column_name].std()

In [19]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [ ]:
df=df.drop("max")

In [28]:
idx=df.index[df.index=='max'][-1]
df=df.drop(idx)

In [23]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,0.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,0.0

In [21]:
# preprocess salary column:
data["salary"]=data["salary"].fillna(0)

In [38]:
df=df.drop(df.index[11])

In [39]:
df

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,198702.325581
median,108.0,67.0,65.0,66.0,71.0,62.0,240000.0
mode,1,62.0,63.0,65.0,60.0,56.7,0.0
25%,54.5,60.6,60.9,61.0,60.0,57.945,0.0
75%,161.5,75.7,73.0,72.0,83.5,66.255,282500.0
max,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,282500.0
MUL*1.5,160.5,22.65,18.15,16.5,35.25,12.465,423750.0
upper_outlier,322.0,98.35,91.15,88.5,118.75,78.72,706250.0
lower_outlier,-106.0,37.95,42.75,44.5,24.75,45.48,-423750.0
min,1,40.89,37.0,50.0,50.0,51.21,0.0
var,3870.0,117.228377,118.755706,54.151103,176.251018,34.028376,23957135274.940235
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,154780.926716
maaxx,215,89.4,97.7,91.0,98.0,77.89,940000.0